// CREATE DATABASE IntituteProject;
// USE IntituteProject;
// CREATE TABLE StaffSalaries(
    // ID bigint,
    // Year varchar(50),
    // Month varchar(50),
    // Name varchar(50),
    // Designation varchar(50),
    // PayScale varchar(100),
    // Level int,
    // PayMatrix bigint,
    // AdditionalIncrement bigint,
    // HRA bigint,
    // CCA bigint,
    // EPF bigint,
    // GSLI bigint,
    // HouseRent bigint,
    // WaterCharge bigint,
    // Mobile bigint,
    // TDS bigint,
    // DA bigint,
    // GrandTotal bigint,
    // Total bigint,
    // Amount bigint
//     PRIMARY KEY (ID, Year, Month)
// // );
    ID, 
    Year, 
    Month, 
    Name ,
    Designation,
    PayScale ,
    Level   ,
    AdditionalIncrement, 
    HRA ,
    CCA,
    EPF ,
    GSLI ,
    HouseRent, 
    WaterCharge,
    ElectricCharge, 
    Mobile ,
    TDS ,
    DA,
    GrandTotal, 
    Total ,
    Amount 